_target_: tracklab.wrappers.BotSORT_bm

cfg:
  # weights can be downloaded from :
  # https://github.com/mikel-brostrom/boxmot/tree/master
  # https://drive.google.com/uc?id=1vduhq5DpN2q1g4fYEZfPI17MJeh9qyrA
  model_weights: ${model_dir}/reid/clip_duke.pt
  fp16: false

  min_confidence: 0

  hyperparams:
  #   appearance_thresh: 0.25  # default = 0.25
  #   cmc_method: ecc  # default = sparseOptFlow
  #   frame_rate: 30  # default = 30
  #   lambda_: 0.985  # default = 0.985
  #   match_thresh: 0.8 # default = 0.8
  #   new_track_thresh: 0.6  # default = 0.6
  #   proximity_thresh: 0.5  # default = 0.5
    track_buffer: 30  # default = 30
  #   track_high_thresh: 0.5  # default = 0.45
